# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculateIsochroneRcpp <- function(from, to, cost, start_nodes, lim, num_cores) {
    .Call(`_GeoRouteR_calculateIsochroneRcpp`, from, to, cost, start_nodes, lim, num_cores)
}

