# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

graph_create <- function(edge_from, edge_to, edge_cost, edge_dist, node_name, node_x, node_y, crs) {
    .Call(`_GeoRouteR_graph_create`, edge_from, edge_to, edge_cost, edge_dist, node_name, node_x, node_y, crs)
}

graph_edges <- function(p) {
    .Call(`_GeoRouteR_graph_edges`, p)
}

graph_nodes <- function(p) {
    .Call(`_GeoRouteR_graph_nodes`, p)
}

graph_node_dict <- function(p) {
    .Call(`_GeoRouteR_graph_node_dict`, p)
}

graph_crs <- function(p) {
    .Call(`_GeoRouteR_graph_crs`, p)
}

calculate_isochrone <- function(graph_ptr, start_nodes_sexp, lim_sexp) {
    .Call(`_GeoRouteR_calculate_isochrone`, graph_ptr, start_nodes_sexp, lim_sexp)
}

